[package]
name = "nestos-installer"
repository = "https://gitee.com/openeuler/nestos-installer"
license = "Apache-2.0 "
edition = "2018"
exclude = ["/.cci.jenkinsfile", "/.github", "/.gitignore", "/Dockerfile"]
description = "Installer for NestOS"
version = "0.10.0"

[package.metadata.release]
sign-commit = true
disable-push = true
disable-publish = true
pre-release-commit-message = "cargo: nestos-installer release {{version}}"
post-release-commit-message = "cargo: development version bump"
tag-message = "nestos-installer v{{version}}"

[features]
# rdcore is only useful inside the initrd of a NestOS system
rdcore = []

[lib]
name = "libcoreinst"
path = "src/lib.rs"

[[bin]]
name = "nestos-installer"
path = "src/main.rs"

[[bin]]
name = "rdcore"
path = "src/bin/rdcore/main.rs"
required-features = ["rdcore"]

[profile.release]
lto = true

[dependencies]
anyhow = ">= 1.0.38, < 2"
bincode = "^1.3"
byte-unit = ">= 3.1.0, < 5.0.0"
clap = "^2.33"
cpio = "^0.2"
flate2 = "^1.0"
glob = "^0.3"
gptman = { version = ">= 0.7, < 0.9", default-features = false }
hex = "^0.4"
lazy_static = "^1.4"
libc = "^0.2"
nix = ">= 0.17, < 0.22"
openat-ext = ">= 0.1.4, < 0.3"
openssl = "^0.10"
pipe = ">= 0.3, < 0.5"
regex = ">= 1.4, < 1.6"
reqwest = { version = ">= 0.10, < 0.12", features = ["blocking"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
tempfile = ">= 3.1, < 4"
url = ">= 2.1, < 3.0"
uuid = { version = "^0.8", features = ["v4"] }
walkdir = "^2.3"
xz2 = "^0.1"

[dev-dependencies]
maplit = "^1.0"

[target.'cfg(target_arch = "s390x")'.dependencies]
mbrman = { version = ">= 0.3, < 0.5", default-features = false }
rand = ">= 0.7, < 0.9"

# In CoreOS CI we test installation from a compressed image created with
# `cosa compress --fast`.  This is unacceptably slow if the gunzip inner
# loops are compiled unoptimized.
[profile.dev.package.adler]
opt-level = 3
[profile.dev.package.crc32fast]
opt-level = 3
[profile.dev.package.miniz_oxide]
opt-level = 3
